name: Node.js
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: {}

jobs:
  bump-deps:
    name: Bump Dependencies
    uses: trynoice/.github/.github/workflows/bump-npm-deps.yaml@main
    with:
      build-command: sh -c 'npm run build && npm run typecheck'
    secrets:
      noice-bot-github-token: ${{ secrets.BOT_PAT }}
